plugins { id 'fabric-loom' version '1.8.13' }
version = '1.1.0'
group = 'dev.vinuspanel'
base.archivesName = 'vinus-players-fabric-1.20.1'
repositories { mavenCentral() }
dependencies { minecraft 'com.mojang:minecraft:1.20.1'; mappings loom.officialMojangMappings(); modImplementation 'net.fabricmc:fabric-loader:0.16.10' }
sourceSets.main.java.srcDir '../common'
tasks.withType(JavaCompile).configureEach { options.release = 17 }
