plugins { id 'net.minecraftforge.gradle' version '6.0.54' }
version='1.1.0'; group='dev.vinuspanel'; base.archivesName='vinus-players-forge-1.20.1'
java.toolchain.languageVersion=JavaLanguageVersion.of(17)
minecraft { mappings channel:'official',version:'1.20.1' }
repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.20.1-47.3.0' }
sourceSets.main.java.srcDir '../common'
jar.finalizedBy('reobfJar')
